services:
  - type: web
    name: izumi
    repo: https://github.com/Akshay-Eypz/izumi-bot.git
    branch: main
    env: docker
    dockerfilePath: docker pull ghcr.io/eypzffx/izumi:latest
    plan: free
    autoDeploy: false
    envVars:
      - key: RENDER_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
      - key: MODE
        value: "private"
      - key: PORT
        value: "8000"
